name: Node.js CI

# Trigger events for manual run and cron schedule
on:
  workflow_dispatch:
    inputs:
      TARGET_ENVIRONMENT:
        description: "What environment do you want to deploy to?"
        required: true
        type: choice
        options:
          - none
          - sandbox
          - dev
          - qa
          - stage-eu
          - prod-eu
          - prod-eu-dr

      TERRAFORM_COMMAND:
        description: "Should terraform resources be created or destroyed?"
        required: true
        type: choice
        options:
          - apply
          - destroy

      DEPLOY:
        description: "Should the compiled code be pushed as a docker container and deployed via terraform?"
        required: true
        type: choice
        options:
          - no
          - yes

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      SAMPLE: "my ENV"
      SECRET_KEY: ${{ secrets.SECRET_KEY }}

    steps:
      - name: Set Environment Specific Variables
        if: ${{ github.event.inputs.TARGET_ENVIRONMENT != 'none' }}
        run: |
          TARGET_ENVIRONMENT="${{ github.event.inputs.TARGET_ENVIRONMENT }}"
          
          case "$TARGET_ENVIRONMENT" in
            "sandbox")
              ENVIRONMENT_SHORT_NAME="sb"
              ;;
            "dev")
              ENVIRONMENT_SHORT_NAME="dev"
              ;;
            "qa")
              ENVIRONMENT_SHORT_NAME="qa"
              ;;
            "stage-eu")
              ENVIRONMENT_SHORT_NAME="stgeu"
              ;;
            "prod-eu")
              ENVIRONMENT_SHORT_NAME="prodeu"
              ;;
            "prod-eu-dr")
              ENVIRONMENT_SHORT_NAME="prodeudr"
              ;;
            *)
              echo "Specified target environment '${TARGET_ENVIRONMENT}' is not supported.  Pipeline aborted."
              exit 1
              ;;
          esac

          # Set the Docker registry URL
          DOCKER_REGISTRY_URL="amazon.com"
          TERRAFORM_STATE_ACCOUNT_ID="123456"

          # Echo the variables for visibility
          echo "ENVIRONMENT_SHORT_NAME: $ENVIRONMENT_SHORT_NAME"
          echo "TERRAFORM_STATE_ACCOUNT_ID: $TERRAFORM_STATE_ACCOUNT_ID"
          echo "DOCKER_REGISTRY_URL: $DOCKER_REGISTRY_URL"

      - name: hash
        run: |
          sha="${GITHUB_SHA}"
          if [[ "${{ github.event.inputs.TARGET_ENVIRONMENT }}" != "none" && "${{ github.event.inputs.DEPLOY }}" == "true" ]]; then
            echo "DISPLAY_NAME=${{ github.event.inputs.TARGET_ENVIRONMENT }} - ${sha:0:7}" >> $GITHUB_ENV
          else
            echo "DISPLAY_NAME=${sha:0:7}" >> $GITHUB_ENV
          fi

      - name: Print DISPLAY_NAME
        run: echo "DISPLAY_NAME is $DISPLAY_NAME"

      - name: Clean Git Repository
        run: git clean -xdf

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm install

      - name: Print Secret
        run: |
          echo "SECRET KEY $SECRET_KEY"
          echo "SAMPLE $SAMPLE"

      - name: Run script
        run: node index.js
